### ISSUE TITLE
 Unable to open database file - phpunit.phar/phpunit/Framework/TestSuite.php

### ISSUE THREAD

**Issue by manishkumar-dsi** [kenjis/ci-hmvc-ci-phpunit-test#2]
Hi,

I have followed exact steps given in documentation but when I am running phpunit command then getting the following issue:

```
PHPUnit 5.5.0 by Sebastian Bergmann and contributors.


Database error: A Database Error Occurred

        SQLSTATE[HY000] [14] unable to open database file
        Filename: phar://D:/phpunit/phpunit.phar/phpunit/Framework/TestSuite.php
        Line Number: 753

```
Though if I run
`phpunit . `

from tests folder then it is not throwing any error but there is not test case is running.

Please suggest the solution.

**Comment by kenjis** [comment]
@manishkumar-dsi Thanks for your report.

I've pushed the fix for it. https://github.com/kenjis/ci-hmvc-ci-phpunit-test/commit/40282d61ab9026b199d84348c6c639ca675a9bf7
