### ISSUE TITLE
request method return empty string

### ISSUE THREAD

**Issue by MrBars24** [kenjis/ci-hmvc-ci-phpunit-test#6]
I am trying to integrate phpunit-test on our project upon testing

this code return empty string on my end
```$output = $this->request('GET','home/index');```

here is my controller code
```php
<?php defined('BASEPATH') OR exit('No direct script access allowed');

class Home extends MY_Controller {

	public $page_title = "Home";
	private $promo;

	function __construct() {
		parent::__construct();
		$this->load->helper('promos/promo');
		$this->promo = $this->session->userdata('promo');
    }

	public function index() {
		if (user_login()) {
			$this->middle = 'public/home';
			$this->public_layout();
		} else {
			$page_option = array('page_title' => $this->page_title, 'page' => 'home');

			$this->data['page'] = $page_option;
			page_init($page_option);

			$this->middle = 'public/home';
			$this->public_layout();
		}
	}
}
```

**Comment by kenjis** [comment]
@MrBars24 Are you using codeigniter-modular-extensions-hmvc?
This repo is sample for codeigniter-modular-extensions-hmvc.

And the session does not work with phpunit, because it runs on CLI.
Does your code work when `$this->session->userdata('promo')` returns null?

**Comment by MrBars24** [comment]
@kenjis  yes I am using codeigniter-modular-extensions-hmvc
and yes this code will run even if we disregard session

**Comment by kenjis** [comment]
@MrBars24 What if you run a test for CodeIgniter Welcome controller?

**Comment by MrBars24** [comment]
@kenjis I am able to run it now but new error comes out

**CIPHPUnitTestExitException: Unable to locate the specified class: Session.php**

**Comment by kenjis** [comment]
@MrBars24 What version of ci-phpunit-test do you use?
Do you use the latest ci-phpunit-test?

**Comment by ayokay123** [comment]
hey, i implemented ci-phpunit-test into my project and i got an error when i run the welcome_test ` Failed asserting that '/index is not found' contains "<title>Welcome to CodeIgniter</title>" ` and that normal because i dont have but when i try for other controller it returns empty string

**Comment by kenjis** [comment]
@ayokay123 This repo is just a sample.

If you have issues on ci-phpunit-test, please file at:
https://github.com/kenjis/ci-phpunit-test
